#!/usr/bin/env bash

[[ -z $ZOUL_LOG ]] && . zoul-log

log_enter_hooks
echo "$PWD @ $0 ${*@Q}" &>>"$stdallRedir"
exit 0

# while read oldSha newSha extraInfo; do
#   echo "$PWD @ oldSha=${oldSha::7} newSha=${newSha::7}" extraInfo=$extraInfo &>>"$stdallRedir"
# done

# exit 0
