<!--
  # Cpp.PlatformToolset.props
  + Configuration, IsDebug, IsRelease, Solution*, Project*
-->
<Project>
    
  <!-- PlatformToolset -->
  <Import Project="Cpp.PlatformToolset.props" Condition="'$(PlatformToolset)' == ''"/>

  <!-- Configuration, IsDebug, IsRelease -->
  <PropertyGroup>
    <IsDebug>false</IsDebug>
    <IsRelease>false</IsRelease>
    
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <IsDebug       Condition="$(Configuration.StartsWith('Debug',   StringComparison.OrdinalIgnoreCase))">true</IsDebug>
    <IsRelease     Condition="$(Configuration.StartsWith('Release', StringComparison.OrdinalIgnoreCase))">true</IsRelease>
  </PropertyGroup>

  <!-- Resolves missing properties when using 'dotnet msbuild' command. -->
  <PropertyGroup>
    <SolutionName  Condition="'$(SolutionName)'  == ''">*Undefined*</SolutionName>
    <SolutionDir   Condition="'$(SolutionDir)'   == ''">$(MSBuildProjectDirectory)\</SolutionDir>
    <SolutionPath  Condition="'$(SolutionPath)'  == ''">*Undefined*</SolutionPath>
    <ProjectName   Condition="'$(ProjectName)'   == ''">$([System.IO.Path]::GetFileNameWithoutExtension('$(MSBuildProjectFile)'))</ProjectName>
    <ProjectDir    Condition="'$(ProjectDir)'    == ''">$(MSBuildProjectDirectory)\</ProjectDir>
    <ProjectDir    Condition="'$(ProjectDir)'    == ''">$(SolutionDir)</ProjectDir>
    <ProjectPath   Condition="'$(ProjectPath)'   == ''">$(ProjectDir)$(MSBuildProjectFile)</ProjectPath>
  </PropertyGroup>

</Project>
