<!--
Inputs
  [WinRuntimePrefix]
  [OsxRuntimePrefix]
  [LinuxRuntimePrefix]
  [RuntimeIdentifier]
  BuildWin
  BuildOsx
  BuildLinux
Outputs
  WinRuntimePrefix
  OsxRuntimePrefix
  LinuxRuntimePrefix
  RuntimeIdentifier
  RuntimeOs
  RuntimeFolder
  @RuntimeIdentifier
-->
<Project TreatAsLocalProperty="RuntimeIdentifier;WinRuntimePrefix;OsxRuntimePrefix;LinuxRuntimePrefix">

  <PropertyGroup>
    <BootRuntimeImported>true</BootRuntimeImported>
  </PropertyGroup>

  <Import Project="Boot.Platform.props" />
  <Import Project="Boot.CrossBuild.props" />

  <!--
  Supported RuntimeIdentifier prefix
  Starting with .NET10, when packing as a tool, the 'RuntimeIdentifiers' property should not be set
  to avoid creates RID-specific packages.
  see https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/10.0/dotnet-tool-pack-publish
  -->
  <PropertyGroup Condition="!$(RuntimeIdentifier.StartsWith('browser')) And '$(PackAsTool)' != 'true'">
    <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)' == ''">win-x86;win-x64;win-arm64;osx-x64;osx-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <!-- Supported RuntimeIdentifier prefix  -->
  <PropertyGroup>
    <WinRuntimePrefix   Condition="'$(WinRuntimePrefix)'   == ''">win</WinRuntimePrefix>
    <OsxRuntimePrefix   Condition="'$(OsxRuntimePrefix)'   == ''">osx</OsxRuntimePrefix>
    <LinuxRuntimePrefix Condition="'$(LinuxRuntimePrefix)' == ''">linux</LinuxRuntimePrefix>
  </PropertyGroup>

  <!-- RuntimeIdentifier property -->
  <Choose>
    <When Condition="$(TargetFramework.StartsWith('netstandard'))">
      <PropertyGroup>
        <RuntimeIdentifier />
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="'$(ZouAgentType)' == '' And '$(RuntimeIdentifier)' == '' And '$(RuntimePlatform)' != ''">
        <RuntimeIdentifier Condition="$([MSBuild]::IsOsPlatform(Windows))">$(WinRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
        <RuntimeIdentifier Condition="$([MSBuild]::IsOsPlatform(OSX))">$(OsxRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
        <RuntimeIdentifier Condition="$([MSBuild]::IsOsPlatform(Linux))">$(LinuxRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  
  <!-- RuntimeOs and RuntimeFolder properties -->
  <PropertyGroup Condition="'$(ZouAgentType)' == ''">
    <RuntimeOs Condition="$([MSBuild]::IsOsPlatform(Windows))">win</RuntimeOs>
    <RuntimeOs Condition="$([MSBuild]::IsOsPlatform(OSX))">osx</RuntimeOs>
    <RuntimeOs Condition="$([MSBuild]::IsOsPlatform(Linux))">linux</RuntimeOs>
    <RuntimeFolder Condition="'$(RuntimePlatform)' == ''">$(RuntimeOs)</RuntimeFolder>
    <RuntimeFolder Condition="'$(RuntimePlatform)' != ''">$(RuntimeOs)-$(RuntimePlatform)</RuntimeFolder>
  </PropertyGroup>
  
  <!-- RuntimeOs items -->
  <ItemGroup Condition="'$(ZouAgentType)' != ''">
    <RuntimeOs Condition="$(BuildWin)" Include="win">
      <RuntimeIdentifier Condition=" $(RuntimeIdentifier.StartsWith('win'))">$(RuntimeIdentifier)</RuntimeIdentifier>
      <RuntimeIdentifier Condition="!$(RuntimeIdentifier.StartsWith('win')) And '$(RuntimePlatform)' != ''">$(WinRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
      <RuntimeFolder Condition="'$(RuntimePlatform)' == ''">win</RuntimeFolder>
      <RuntimeFolder Condition="'$(RuntimePlatform)' != ''">win-$(RuntimePlatform)</RuntimeFolder>
    </RuntimeOs>
    <RuntimeOs Condition="$(BuildOsx)" Include="osx">
      <RuntimeIdentifier Condition=" $(RuntimeIdentifier.StartsWith('osx'))">$(RuntimeIdentifier)</RuntimeIdentifier>
      <RuntimeIdentifier Condition="!$(RuntimeIdentifier.StartsWith('osx')) And '$(RuntimePlatform)' != ''">$(OsxRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
      <RuntimeFolder Condition="'$(RuntimePlatform)' == ''">osx</RuntimeFolder>
      <RuntimeFolder Condition="'$(RuntimePlatform)' != ''">osx-$(RuntimePlatform)</RuntimeFolder>
    </RuntimeOs>
    <RuntimeOs Condition="$(BuildLinux)" Include="linux">
      <RuntimeIdentifier Condition=" $(RuntimeIdentifier.StartsWith('linux'))">$(RuntimeIdentifier)</RuntimeIdentifier>
      <RuntimeIdentifier Condition="!$(RuntimeIdentifier.StartsWith('linux')) And '$(RuntimePlatform)' != ''">$(LinuxRuntimePrefix)-$(RuntimePlatform)</RuntimeIdentifier>
      <RuntimeFolder Condition="'$(RuntimePlatform)' == ''">linux</RuntimeFolder>
      <RuntimeFolder Condition="'$(RuntimePlatform)' != ''">linux-$(RuntimePlatform)</RuntimeFolder>
    </RuntimeOs>
  </ItemGroup>

</Project>
