<Project InitialTargets="TraceHookZouBuildRedistProps">
  
  <!-- Import the first 'zou.build.redist.props' found in the local project directory or above -->
  <PropertyGroup>
    <ZouBuildRedistProps>$([MSBuild]::GetPathOfFileAbove('zou.build.redist.props', '$(MSBuildProjectDirectory)'))</ZouBuildRedistProps>
    <!-- For backward compatibility -->
    <ZouBuildRedistProps Condition="'$(ZouBuildRedistProps)' == ''">$([MSBuild]::GetPathOfFileAbove('zou.build.props', '$(MSBuildProjectDirectory)'))</ZouBuildRedistProps>
  </PropertyGroup>
  <Import Project="$(ZouBuildRedistProps)" Condition="Exists('$(ZouBuildRedistProps)')" />

  <Target Name="TraceHookZouBuildRedistProps" Condition="'$(HookDebug)' == 'true'">
    <Message Importance="high" Text=" " />
    <Message Importance="high" Text="$(T0)$([MSBuild]::MakeRelative('$(BundleDir)', '$(MSBuildThisFileFullPath)')) ($(BundleRelativeProjectPath))$(NC)" />

    <Message Importance="high" Text="ZouBuildRedistProps = $(ZouBuildRedistProps)" />
  </Target>
</Project>
