<Project InitialTargets="TraceHookZouBuildRedistProps">
  
  <!-- Import the first 'zou.build.redist.props' found in the local project directory or above -->
  <PropertyGroup>
    <ZouBuildRedistProps>$([MSBuild]::GetPathOfFileAbove('zou.build.redist.props', '$(MSBuildProjectDirectory)'))</ZouBuildRedistProps>
    <!-- For backward compatibility -->
    <ZouBuildRedistProps Condition="'$(ZouBuildRedistProps)' == ''">$([MSBuild]::GetPathOfFileAbove('zou.build.props', '$(MSBuildProjectDirectory)'))</ZouBuildRedistProps>
  </PropertyGroup>
  <Import Project="$(ZouBuildRedistProps)" Condition="Exists('$(ZouBuildRedistProps)')" />

  <Target Name="TraceHookZouBuildRedistProps" Condition="'$(RedistDebug)' != ''">
    <Message Importance="high" Text="$(T0)$(MSBuildThisFile) ($(MSBuildProjectFile))$(NC)" />
    <Message Importance="high" Text="ZouBuildRedistProps = $(ZouBuildRedistProps)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>
