<Project InitialTargets="TraceHookZouBuildTfmProps">
  
  <!-- Import the first 'zou.build.tfm.props' found in the local project directory or above -->
  <PropertyGroup>
    <ZouBuildTfmProps>$([MSBuild]::GetPathOfFileAbove('zou.build.tfm.props', '$(MSBuildProjectDirectory)'))</ZouBuildTfmProps>
  </PropertyGroup>
  <Import Project="$(ZouBuildTfmProps)" Condition="Exists('$(ZouBuildTfmProps)')" />

  <Target Name="TraceHookZouBuildTfmProps" Condition="'$(TfmHookDebug)' != ''">
    <Message Importance="high" Text="$(T0)$(MSBuildThisFile) ($(MSBuildProjectFile))$(NC)" />
    <Message Importance="high" Text="ZouBuildTfmProps = $(ZouBuildTfmProps)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>
