<!-- Trace Project and Package References -->
<Project  InitialTargets="TraceReferencesTargets">

  <PropertyGroup>
    <ReferencesTargetsImported>true</ReferencesTargetsImported>
  </PropertyGroup>

  <Target Name="TraceReferencesTargets" Condition="'$(RefDebug)' == 'true'">
    <Message Importance="high" Text="$(T0)$(MSBuildThisFile) ($(MSBuildProjectFile))$(NC)" />
    <Message Importance="high" Text="BuildType        = $(BuildType)" />
    <Message Importance="high" Text="TargetFramework  = $(TargetFramework)"  Condition="!$(MultiTargeting)" />
    <Message Importance="high" Text="TargetFrameworks = $(TargetFrameworks)" Condition=" $(MultiTargeting)" />
    
    <!--<Message Importance="high" Text=" " Condition="@(ProjectReference->Count()) > 0" />-->
    <LogItems Items="@(ProjectReference)" Title="ProjectReference" />
    
    <!--<Message Importance="high" Text=" " Condition="@(PackageReference->Count()) > 0" />-->
    <LogItems Items="@(PackageReference)" Title="PackageReference" />
    
    <Message Importance="high" Text=" " />
  </Target>
  
</Project>
