<Project InitialTargets="TraceTargetFrameworkProps">

  <PropertyGroup>
    <TargetFrameworkImported>true</TargetFrameworkImported>
  </PropertyGroup>

  <!--
  CoreTargetFramework backward compatibility:
  When CoreTargetFramework is specified, either on the CLI or in the root Directory.Build.props
  we will use it as the ZouTargetFramework, which is the new property name for the target framework control.
  -->
  <PropertyGroup Condition="'$(CoreTargetFramework)' != '' And '$(ZouTargetFramework)' == '' And '$(MultiTargeting)' != 'true'">
    <ZouTargetFramework>$(CoreTargetFramework)</ZouTargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ZouTargetFramework)' != ''">
    <_ZouTfmVer>$([MSBuild]::GetTargetFrameworkVersion('$(ZouTargetFramework)', 1))</_ZouTfmVer>
    <_ZouTfmFull Condition="'$(_ZouTfmVer)' &lt;= '4.8'">true</_ZouTfmFull>
    <_ZouTfmFull Condition="'$(_ZouTfmFull)' == ''">false</_ZouTfmFull>
    <CoreTargetFramework Condition="'$(_ZouTfmFull)' != 'true'">$(ZouTargetFramework)</CoreTargetFramework>
    <FullTargetFramework Condition="'$(_ZouTfmFull)' == 'true'">$(ZouTargetFramework)</FullTargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <CoreTargetFramework     Condition="'$(CoreTargetFramework)'     == ''">net10.0</CoreTargetFramework>
    <FullTargetFramework     Condition="'$(FullTargetFramework)'     == ''">net4.8</FullTargetFramework>
    <WineTargetFramework     Condition="'$(WineTargetFramework)'     == ''">netcoreapp3.1</WineTargetFramework>
    <WindowsTargetFramework  Condition="'$(WindowsTargetFramework)'  == ''">$(CoreTargetFramework)-windows</WindowsTargetFramework>
    <BrowserTargetFramework  Condition="'$(BrowserTargetFramework)'  == ''">$(CoreTargetFramework)-browser</BrowserTargetFramework>

    <CoreTargetFrameworks    Condition="'$(CoreTargetFrameworks)'    == ''">net8.0;net10.0</CoreTargetFrameworks>
    <WindowsTargetFrameworks Condition="'$(WindowsTargetFrameworks)' == ''">net8.0-windows;net10.0-windows</WindowsTargetFrameworks>
    <BrowserTargetFrameworks Condition="'$(BrowserTargetFrameworks)' == ''">net8.0-browser;net10.0-browser</BrowserTargetFrameworks>
    <NetStdTargetFrameworks  Condition="'$(NetStdTargetFrameworks)'  == ''">netstandard2.0;netstandard2.1</NetStdTargetFrameworks>
  </PropertyGroup>

  <!-- Start the TFM babouchka -->
  <Import Project="hook.zou.build.tfm.props" Condition="'$(ZouBuildTfmProps)' == ''"/>

  <Target Name="TraceTargetFrameworkProps" Condition="'$(TfmDefDebug)' == 'true'">
    <Message Importance="high" Text="$(T0)$([MSBuild]::MakeRelative('$(BundleDir)', '$(MSBuildThisFileFullPath)')) ($(BundleRelativeProjectPath))$(NC)" />

    <Message Importance="high" Text="_ZouTfmVer              = $(_ZouTfmVer)" />
    <Message Importance="high" Text="_ZouTfmFull             = $(_ZouTfmFull)" />
    <Message Importance="high" Text="ZouTargetFramework      = $(ZouTargetFramework)" />
    <Message Importance="high" Text="CoreTargetFramework     = $(CoreTargetFramework)" />
    <Message Importance="high" Text="FullTargetFramework     = $(FullTargetFramework)" />
    <Message Importance="high" Text="WindowsTargetFramework  = $(WindowsTargetFramework)" />
    <Message Importance="high" Text="ZouTargetFrameworks     = $(ZouTargetFrameworks)" />
    <Message Importance="high" Text="CoreTargetFrameworks    = $(CoreTargetFrameworks)" />
    <Message Importance="high" Text="WindowsTargetFrameworks = $(WindowsTargetFrameworks)" />
    <Message Importance="high" Text="BrowserTargetFrameworks = $(BrowserTargetFrameworks)" />
    <Message Importance="high" Text="NetStdTargetFrameworks  = $(NetStdTargetFrameworks)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>
