<Project InitialTargets="TraceTargetFrameworkProps">

  <PropertyGroup>
    <TargetFrameworkImported>true</TargetFrameworkImported>
    
    <MultiTargeting          Condition="'$(MultiTargeting)'          == ''">false</MultiTargeting>

    <FullTargetFramework     Condition="'$(FullTargetFramework)'     == ''">net48</FullTargetFramework>
    <CoreTargetFramework     Condition="'$(CoreTargetFramework)'     == ''">net10.0</CoreTargetFramework>
    <WineTargetFramework     Condition="'$(WineTargetFramework)'     == ''">netcoreapp3.1</WineTargetFramework>
    <WindowsTargetFramework  Condition="'$(WindowsTargetFramework)'  == ''">$(CoreTargetFramework)-windows</WindowsTargetFramework>
    <BrowserTargetFramework  Condition="'$(BrowserTargetFramework)'  == ''">$(CoreTargetFramework)-browser</BrowserTargetFramework>

    <CoreTargetFrameworks    Condition="'$(CoreTargetFrameworks)'    == ''">net8.0;net10.0</CoreTargetFrameworks>
    <WindowsTargetFrameworks Condition="'$(WindowsTargetFrameworks)' == ''">net8.0-windows;net10.0-windows</WindowsTargetFrameworks>
    <BrowserTargetFrameworks Condition="'$(BrowserTargetFrameworks)' == ''">net8.0-browser;net10.0-browser</BrowserTargetFrameworks>
  </PropertyGroup>

  <Target Name="TraceTargetFrameworkProps" Condition="'$(TfmDefDebug)' == 'true'">
    <Message Importance="high" Text="$(T0)$(MSBuildThisFile) ($(MSBuildProjectFile))$(NC)" />
    <Message Importance="high" Text="MultiTargeting          = $(MultiTargeting)" />
    <Message Importance="high" Text="CoreTargetFramework     = $(CoreTargetFramework)" />
    <Message Importance="high" Text="FullTargetFramework     = $(FullTargetFramework)" />
    <Message Importance="high" Text="WindowsTargetFramework  = $(WindowsTargetFramework)" />
    <Message Importance="high" Text="CoreTargetFrameworks    = $(CoreTargetFrameworks)" />
    <Message Importance="high" Text="WindowsTargetFrameworks = $(WindowsTargetFrameworks)" />
    <Message Importance="high" Text="BrowserTargetFrameworks = $(BrowserTargetFrameworks)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>
