<Project InitialTargets="TraceTFM">
  <!--
  TargetFrameworks
  TFMx = TargetFrameworkSystem
  TFMs = TargetFrameworks
  ZAG  = ZouAgentType
  CLI  = Command Line build
  VST  = Visual Studio build
  
  TFMx TFMs ZAG -> TFM   TFMs
   0    0    0      1     0
   0    0    1      0     0
   0    1           0     1
   1    0           1     0
   1    1   CLI     1     1
   1    1   VST     1     0
  -->

  <Choose>
    <When Condition="'$(TargetFramework)' == '' And '$(TargetFrameworks)' == ''">
      <PropertyGroup>
        <Tfm0>1 TFMx=0 TFMs=0</Tfm0>
        <TargetFramework>$(CoreTargetFramework)</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="'$(TargetFramework)' == '' And '$(TargetFrameworks)' != ''">
      <PropertyGroup>
        <Tfm0>2 TFMx=0 TFMs=1</Tfm0>
        <!--<TargetFramework>$(TargetFrameworks.Split(';')[0].Trim())</TargetFramework>
        <TargetFrameworks />-->
      </PropertyGroup>
    </When>
    <When Condition="'$(TargetFramework)' != '' And '$(TargetFrameworks)' == ''">
      <PropertyGroup>
        <Tfm0>3 TFMx=1 TFMs=0</Tfm0>
      </PropertyGroup>
    </When>
    <When Condition="'$(TargetFramework)' != '' And '$(TargetFrameworks)' != ''">
      <PropertyGroup>
        <Tfm0>4 TFMx=1 TFMs=1</Tfm0>
      </PropertyGroup>
    </When>
  </Choose>

  <PropertyGroup>
    <BuildLoc>VST</BuildLoc>
    <BuildLoc Condition="'$(BuildingInsideVisualStudio)' == ''">CLI</BuildLoc>
    <Tfm1>TFMSys='$(TargetFrameworkSystem)' CoreTFM='$(CoreTargetFramework)' TFMI='$(TargetFrameworkImport)' TFMs='$(TargetFrameworks)' TFM='$(TargetFramework)'</Tfm1>
  </PropertyGroup>

  <Target Name="TraceTFM">
    <!--<Message Importance="high" Text="%24 [$(MSBuildProjectFile)] TargetFramework.props" />-->
    <Message Importance="high" Text="$(Tfm0) $(BuildLoc) $(Tfm1) : $(MSBuildProjectFile)" />
    <!--<Message Importance="High" Text="TargetFramework         = $(TargetFramework)" />
    <Message Importance="High" Text="TargetFrameworks        = $(TargetFrameworks)" />
    <Message Importance="High" Text="FullTargetFramework     = $(FullTargetFramework)" />
    <Message Importance="High" Text="CoreTargetFramework     = $(CoreTargetFramework)" />
    <Message Importance="High" Text="WineTargetFramework     = $(WineTargetFramework)" />
    <Message Importance="High" Text="WindowsTargetFramework  = $(WindowsTargetFramework)" />
    <Message Importance="High" Text="CoreTargetFrameworks    = $(CoreTargetFrameworks)" />
    <Message Importance="High" Text="WindowsTargetFrameworks = $(WindowsTargetFrameworks)" />
    <Message Importance="High" Text=" " />-->
  </Target>

</Project>
