<Project InitialTargets="TraceZouTasksProps">
  
  <PropertyGroup>
    <ZouTasksDebugDllPath>$(MSBuildThisFileDirectory)Tasks\bin\Debug\netstandard2.0\Tasks.dll</ZouTasksDebugDllPath>
    <ZouTasksBinzDllPath>$(ZouBinzDir)tasks\Tasks.dll</ZouTasksBinzDllPath>
    <!-- Use debug version builded with Tasks.sln inside Visual Studio -->
    <ZouTasksDllPath Condition="'$(ZouTasksDllPath)' == '' And Exists('$(ZouTasksDebugDllPath)')">$(ZouTasksDebugDllPath)</ZouTasksDllPath>
    <ZouTasksDllPath Condition="'$(ZouTasksDllPath)' == ''">$(ZouTasksBinzDllPath)</ZouTasksDllPath>
  </PropertyGroup>

  <!--
    Import the appropriate tasks based on whether TaskHostFactory is enabled.
    
    - Out of process tasks should be used only when building 'Tasks.csproj' so that MSBuild can load the tasks in a separate process to avoid file in use issues.
    - Out of process tasks should not be used when building normal projects, due to issues with the 'ItemDefinitionGroup' not being forwarded to the out of process task host.
  -->
  <Import Project="zou.Tasks.InProcess.props"    Condition="'$(EnableTaskHostFactory)' != 'true'"/>
  <Import Project="zou.Tasks.OutOfProcess.props" Condition="'$(EnableTaskHostFactory)' == 'true'"/>

  <!-- Launch a Process asynchronously -->
  <UsingTask TaskName="ExecAsync" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <!--The file path is the full path to the executable file to run-->
      <FilePath ParameterType="System.String" Required="true" />
      <!--The arguments should contain all the command line arguments that need to be sent to the application-->
      <Arguments ParameterType="System.String" Required="false" />
      <WorkingDirectory ParameterType="System.String" Required="false" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
  string name = System.IO.Path.GetFileNameWithoutExtension(FilePath);
  Log.LogMessage("Starting {0}...", name);        
  System.Diagnostics.ProcessStartInfo processStartInfo = new System.Diagnostics.ProcessStartInfo(FilePath, Arguments);
  processStartInfo.UseShellExecute = true;
  processStartInfo.WorkingDirectory = WorkingDirectory;
  System.Diagnostics.Process.Start(processStartInfo);
  Log.LogMessage("Finished running process {0}.", name);
  ]]>
      </Code>
    </Task>
  </UsingTask>
  
  <Target Name="TraceZouTasksProps" Condition="'$(ZouTasksDebug)' == 'true' Or '$(MSBuildProjectFile)' == '$(MSBuildThisFile)'">
    <Message Importance="high" Text="$(T0)$([MSBuild]::MakeRelative('$(BundleDir)', '$(MSBuildThisFileFullPath)')) ($(BundleRelativeProjectPath))$(NC)" />

    <Message Importance="high" Text="ZouTasksDebugDllPath = $(ZouTasksDebugDllPath)" />
    <Message Importance="high" Text="ZouTasksDllPath      = $(ZouTasksDllPath)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>

