<!--
Imported by the zou TFM babouchka (zou.build.tfm.props chain),
after the .NET Sdk babouchka (Directory.Build.props chain).

.NET SDK babouchka chain:
=========================
'- module/Directory.Build.props
  '- bundle/Directory.Build.props
    '- zou/Directory.Build.default.props
      '- zou/TargetFramework.props
        |  zou TFM babouchka chain:
        |  ========================
        '- zou/hook.zou.build.tfm.props
          '- module/zou.build.tfm.props
            '- bundle/zou.build.tfm.props
              '- zou/zou.build.tfm.default.props
                '- zou/TargetFramework.build.props
-->
<Project>

  <PropertyGroup>
    <!-- Serialize output when TFM tracing is enabled -->
    <MaxCpuCount Condition="'$(TfmDebug)' == 'true'">1</MaxCpuCount>
  </PropertyGroup>

  <Import Project="TargetFramework.build.props" Condition="'$(TargetFrameworkBuildImported)' == ''"/>

</Project>
