<Project InitialTargets="TraceZouErrorsProps">

  <PropertyGroup>
    <ErrorPoNoMessageIdCode>ZOU1000</ErrorPoNoMessageIdCode>
    <ErrorPoNoMessageId>The command "xgettext" did not find any message IDs in source files.</ErrorPoNoMessageId>

    <ErrorInvalidTfmIdCode>ZOU1001</ErrorInvalidTfmIdCode>
    <ErrorInvalidTfmId>Project '$(MSBuildProjectFile)' does not support any compatible TFM among its declared TargetFrameworks</ErrorInvalidTfmId>

    <WarnTfmOverrideIdCode>ZOU1002</WarnTfmOverrideIdCode>
  </PropertyGroup>

  <Target Name="TraceZouErrorsProps" Condition="'$(ZouErrorsDebug)' == 'true'">
    <Message Importance="high" Text="$(T0)$([MSBuild]::MakeRelative('$(BundleDir)', '$(MSBuildThisFileFullPath)')) ($(BundleRelativeProjectPath))$(NC)" />

    <Message Importance="high" Text="ErrorPoNoMessageIdCode = $(ErrorPoNoMessageIdCode)" />
    <Message Importance="high" Text="ErrorPoNoMessageId     = $(ErrorPoNoMessageId)" />
    <Message Importance="high" Text="ErrorInvalidTfmIdCode  = $(ErrorInvalidTfmIdCode)" />
    <Message Importance="high" Text="ErrorInvalidTfmId      = $(ErrorInvalidTfmId)" />
    <Message Importance="high" Text=" " />
  </Target>
</Project>