<!--
Imported by the zou TFM babouchka (zou.tfm.props chain),
after the .NET Sdk babouchka (Directory.Build.props chain).

.NET SDK babouchka chain:
=========================
'- module/Directory.Build.props
  '- bundle/Directory.Build.props
    '- zou/Directory.Build.default.props
      '- zou/TargetFramework.props
        |  zou TFM babouchka chain:
        |  ========================
        '- zou/hook.zou.tfm.props
          '- module/zou.tfm.props
            '- bundle/zou.tfm.props
              '- zou/zou.tfm.default.props
                '- zou/TargetFramework.build.props
-->
<Project>
  
  <Import Project="TargetFramework.build.props" Condition="'$(TargetFrameworkBuildImported)' == ''"/>

</Project>
