<!--
Imported by the zou REDIST babouchka (zou.build.redist.props chain) through zou agents

zou AGENT Import Order:
=======================
'- module/<agent-project>.msbuildproj
  '- zou/*.Agent.props
    '- zou/Agentprolog.props
      |  zou REDIST babouchka chain:
      |  ===========================
      '- zou/hook.zou.build.redist.props
        '- module/zou.build.redist.props
          '- bundle/zou.build.redist.props
            '- zou/zou.build.redist.default.props
-->
<Project />
