<Project>
  <!-- Keep in sync with zou.Tasks.OutOfProcess.props -->
  <UsingTask TaskName="AddBuildOptions"     AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="MulJoin"             AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="LogItems"            AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="AddFileInfo"         AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="FileUpdate"          AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="CleanPoFile"         AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="CreateHelpMap"       AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="CreateIndexedSubdir" AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="MergePackagesConfig" AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="Lock"                AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="Unlock"              AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="Sleep"               AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="Prompt"              AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="GroupJoin"           AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="LeftOuterJoin"       AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="LoadItems"           AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="SaveItems"           AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="SetEnvVar"           AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="HttpRequest"         AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="Zip"                 AssemblyFile="$(ZouTasksDllPath)" />
  <UsingTask TaskName="GetRealPath"         AssemblyFile="$(ZouTasksDllPath)" />
</Project>

