<Project>
  <PropertyGroup>
    <MultiTargeting>true</MultiTargeting>
    <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">$(CoreTargetFrameworks);$(FullTargetFramework)</TargetFrameworks>
  </PropertyGroup>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
</Project>
