#!/usr/bin/env bash

[[ -z $ZOUL_LOG ]] && . zoul-log

log_enter_hooks
echo "$PWD @ $(basename "$0") ${*@Q}" &>>"$stdallRedir"

previousHead="$1"
newHead="$2"
flag="$3"

echo "$PWD @ previousHead=${previousHead::7} newHead=${newHead::7} flag=$flag" &>>"$stdallRedir"

exit 0
