using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Build.BuildEngine;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace Epsitec.Zou
{
	public class CreateHelpMap: Task
	{
		// Format sample:
		//	HIDR_MAINFRAME	0x20002
		[Required]
		public string[] HelpContextIds
		{
			get;
			set;
		}
		// Format example:
		//	html\intro_cresus.htm
		public string HelpIndexTopic
		{
			get;
			set;
		}
		// Format example:
		//	html\afx_hidd_font.htm
		public string[] HelpContextTopics
		{
			get;
			set;
		}
		// Format example:
		//	hidd_newwizard
		public string[] HelpIgnoreTopics
		{
			get;
			set;
		}
		// Format example:
		//	hid_edit_navprev		navigation
		public string[] HelpSynonymTopics
		{
			get;
			set;
		}
		// Format example:
		//	{ 0x00000, _T("html/intro_cresus.htm") },
		[Output]
		public string[] HelpIndexMappings
		{
			get;
			private set;
		}
		// Format example:
		//	{ 0x2014D, _T("html/hidd_openpreced.htm") },
		[Output]
		public string[] HelpContextMappings
		{
			get;
			private set;
		}
		public override bool			Execute()
		{
			try
			{
				this.HelpIndexMappings   = this.GetElements (null, new[] { this.HelpIndexTopic }, null).ToArray ();
				this.HelpContextMappings = this.GetElements (
					this.HelpContextIds,
					this.HelpContextTopics,
					this.HelpSynonymTopics)
					.ToArray ();
			}
			catch (Exception e)
			{
				this.Log.LogErrorFromException (e);
			}
			return !this.Log.HasLoggedErrors;
		}

		private IEnumerable<string> GetElements(string[] helpIds, string[] topics, string[] synonymTopics)
		{
			// Parse topic relative pathes
			// symbol -> relative-path*
			var symPathLookup = topics
				.ToLookup (topic => Path.GetFileNameWithoutExtension (topic).ToLowerInvariant ());

			// check that topic file names are unique
			symPathLookup.ForEach (item =>
			{
				if (item.Count () > 1)
				{
					var pathes = string.Join (", ", item);
					this.Log.LogError ($"duplicate topic file names are forbidden: {{ {pathes} }}");
				}
			});

			// Parse synonyms
			// symbol -> symbol*
			var synonymLookup = synonymTopics?
				.Select (line => KeyValueRegex.Match (line))
				.Where (match => match.Success)
				.Select (match => new
				{
					Symbol = match.Groups[1].Value,
					Synonym = match.Groups[2].Value.ToLowerInvariant ()
				})
				.ToLookup (a => a.Symbol, a => a.Synonym);

			// Merge synonyms with C/C++ help ID symbols
			// symbol -> values
			var symVals = helpIds?
				.Select (line => KeyValueRegex.Match (line))
				.Where (match => match.Success)
				.SelectMany (match =>
				{
					var symbol = match.Groups[1].Value.ToLowerInvariant ();
					var value = int.Parse (match.Groups[2].Value.Substring (2), NumberStyles.HexNumber);
					var synonyms = synonymLookup?[symbol] ?? Enumerable.Empty<string> ();
					return EnumerableEx
						.Return (symbol)
						.Concat (synonyms)
						.Distinct ()
						.Select (sym => new
						{
							Symbol = sym,
							Value = value
						});
				})
				.ToArray ();

			var ignore = this.HelpIgnoreTopics ?? Enumerable.Empty<string> ();

			// Keep items matching existing topic files or ignore list
			var symValLookup = symVals?
				.Where (a =>
					symPathLookup.Select(item => item.Key).Contains (a.Symbol, StringComparer.OrdinalIgnoreCase) ||
					ignore.Contains (a.Symbol, StringComparer.OrdinalIgnoreCase))
				.ToLookup (a => a.Symbol, a => a.Value);


			// Compute help context mappings
			var valSymLookup = symValLookup?
				.SelectMany (helpId => helpId.Select (value => new
				{
					Value = value,
					Symbol = helpId.Key,
				}))
				.OrderBy (a => a.Symbol)
				.ToLookup (a => a.Value, a => a.Symbol);

			// Compute help index mappings
			valSymLookup = valSymLookup ?? symPathLookup
				.Select (symPath => new
				{
					Value = 0,
					Symbol = symPath.Key,
				})
				.ToLookup (a => a.Value, a => a.Symbol);

			yield return "// This file has been generated by zou, do not modify it.";
			yield return " ";
			if (helpIds != null && valSymLookup.Count == 0)
			{
				this.Log.LogWarning ("could not find any matching help topic");
			}
			else
			{
				foreach (var valSym in valSymLookup)
				{
					var syms = valSym.Except (ignore, StringComparer.OrdinalIgnoreCase).ToArray ();
					var sym = syms.OrderBy (_ => _).First ();
					var url = symPathLookup[sym].FirstOrDefault ()?.Replace ('\\', '/');

					string mapElement;
					if (url == null)
					{
						mapElement = $"{{ 0x{valSym.Key:X5}, _T(\"\") }},	// ignore {sym}";
					}
					else
					{
						mapElement = $"{{ 0x{valSym.Key:X5}, _T(\"{url}\") }},";
					}

					if (syms.Count () > 1)
					{
						var values = string.Join (" and ", syms.Select (x => $"\"{x}\""));
						var warning = $"topics {values} have the same ID (0x{valSym.Key:X4}), using \"{sym}\"...";
						this.Log.LogWarning (warning);
						yield return $"// WARNING: {warning}";
					}
					yield return mapElement;
				}
			}
		}

		// Match this:
		//   KEY	VALUE		// comment
		// But not C++ line comment:
		//   // C++ line comment

		private static readonly Regex KeyValueRegex = new Regex("^(?<!\\s*//\\s*)(\\w+)\\s*(\\w+)", RegexOptions.CultureInvariant | RegexOptions.Compiled);
	}
}
